apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  labels:
    applicationName: test
    name: test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      applicationName: test
  template:
    metadata:
      labels:
        applicationName: test
      annotations:
        traffic.spinnaker.io/load-balancers: ["service test-internal"]
    spec:
      containers:
        - image: nginx
          name: primary
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
