apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: helm-test-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: ReplicaSet
    name: helm-test
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50