apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  labels:
    applicationName: helm-test
  name: helm-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      applicationName: helm-test
  template:
    metadata:
      labels:
        applicationName: helm-test
    spec:
      containers:
        - image: '{{ .Values.image }}:{{ .Values.tag }}'
          name: primary
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80