{{- range $key, $val := .Values.workers }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    applicationName: {{ $key }}
    var: {{ $val.max | quote }}
    min: {{ $val.min | quote }}
  name: {{ $key }}
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      applicationName: {{ $key }}
  template:
    metadata:
      labels:
        applicationName: {{ $key }}
        min: {{ $val.min | quote }}
    spec:
      containers:
        - image: 'nginx'
          name: primary
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $key }}-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: {{ $key }}
  minReplicas: 2
  maxReplicas: {{ $val.max  | quote }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
{{- end }}